### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/main#169]
**Modpack version:**
latest

**Java version:**
curseforge's one

**Description:**
I was looking at a Basic Backpack craft and my friend was putting a blueprint inside an Engineer's workbench, then mc crashed

**When did the crash happen?**
^

**Steps to reproduce:**
idk

**Minecraft crash report:**
https://pastebin.com/DzhXnKHS

**How much RAM did you dedicate to your client and how much RAM does your PC have?**
10gb dedicated, i've 16

**Comment by Atricos** [comment]
We're slowly phasing out the Iron Backpacks mod, because it has multiple issues and it's no longer being developed for 1.12.2.

We're replacing it with Simply Backpacks.

By removing the recipe for the Iron Backpacks in 2.2.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256), this should be fixed now.
