### ISSUE TITLE
Mouse Tweaks - suggestion to add

### ISSUE THREAD

**Issue by Maycke25** [Divine-Journey-2/main#170]
I check for "mouse" but no found  any request

**Modpack version:**
2.X.X

**Describe the request:**
I would like to see mod **Mouse Tweaks** in the modpack.

**Reasons why this should be added:**
light mod, and useful

**Describe alternatives you've considered:**

**Additional context:**
https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks

**Comment by Atricos** [comment]
MouseTweaks is in the pack.
https://www.curseforge.com/minecraft/modpacks/divine-journey-2/relations/dependencies?page=7
![image](https://user-images.githubusercontent.com/24854267/131394526-e77a5065-58bd-48cf-b3e1-f428ad0e67a4.png)

You might have been looking at the server files, where it's not included, since it's a client-only mod.
