### ISSUE TITLE
Imps are too rare

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/main#179]
**Modpack version:**
2.0.0 but it didn't change since then

**Describe the request:**
Imps are too rare.

**Reasons why this should be changed:**
We've been searching for them for like an hour and we've found only one - he dropped one leather. We need 3 leather to complete a quest.

**Describe alternatives you've considered:**
Increase spawn rate

**Comment by Waisse** [comment]
They are indeed so rare I have found exactly none after an entire day of trekking cross the bloated worldgen of the Nether. All kinds of mushrooms, vines and cacti to hurt me plenty, but not a single imp. They just don't spawn.

**Comment by Rongmario** [comment]
They're way too rare, literally have to cheat them in, SAD!

**Comment by sdjjufdki** [comment]
there may be an issue where imps cannot spawn in better nether biomes, but im not 100% syure there

i suggest adding a recipe for imp leather with other more common nether materials, like magma slime or items from better nether biomes, as a way to reduce the rng factor of this item

**Comment by ToasterKoishi** [comment]
I highly suspect this is a biome-related issue (as mentioned above) since, when I was beta-testing, I did actually build some big spawning platforms and imps just would not spawn on them... however, I was assured it was okay, and the imp spawn weight was already increased significantly during the beta, which seemed to have no effect for me. I'm not actually sure if increasing their spawn weight further will have a perceived increase in their actual spawn rate due to the biome issue.

**Comment by ToasterKoishi** [comment]
Ah, I see that a ritual for summoning imps is planned to be added, that should make this a non-issue then. The ritual should definitely be mentioned in the questbook, however.

**Comment by Atricos** [comment]
A Roots Summoning Ritual has been added for an Imp, and I also bumped up their weight from 40 to 80 in `BiomeTweaker/MobSpawning.cfg`.

Fix included in version 2.2.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256

Hopefully, fingers crossed, they'll actually spawn now.
