### ISSUE TITLE
Please update Roots to the latest version

### ISSUE THREAD

**Issue by DarkMatter613** [Divine-Journey-2/main#180]
**Modpack version:**
2.1.1

**Describe the request:**
I would like the latest version of Roots in the modpack.

**Reasons why this should be added:**
The latest version allows for automation of the fey crafter and runic shears from roots as well as adds some nice QoL features.

**Describe alternatives you've considered:**
Perhaps alternative recipes for ingredients made in the fey crafter/runic shears could be added instead.

**Comment by KleinGrrmpf** [comment]
This was specifically discarded because later in the game there is a modular machine that automates the Fey Crafter. So there is no need to update.

**Comment by WaitingIdly** [comment]
What on earth are you talking about Klein. It was postposed because we only realised Roots 3 was out shortly before we had planned to go public.

**Comment by KleinGrrmpf** [comment]
Oh, if that was incorrect, I am deeply sorry about spreading that. That was what I heard last. I thought that Atri specifically didn't want to update because of the Modular Fey Crafter. That was also what I understood from this text message:

![grafik](https://user-images.githubusercontent.com/50833808/131559851-04cb1925-87cd-47f7-ae4f-72130056a571.png)
