### ISSUE TITLE
Crown of the Skies only allowing access to the Aether for one player on a server

### ISSUE THREAD

**Issue by legendcrazyman** [Divine-Journey-2/main#192]
**Modpack version:**
2.1.1

**Description:**
The crown of the skies is consumed for the player who used it on the portal and only that player can go through the Aether portal.

**Steps to reproduce:**
1. Make Crown of the Skies
2. Use on Aether Portal
3. Crown disappears
4. Only that player can enter the Aether

**Expected behavior:**
Everyone can enter the Aether OR The crown does not get consumed
<img width="950" alt="AEther" src="https://user-images.githubusercontent.com/89759794/131758178-c1c32ac3-276d-4140-b878-5e44fc0c9372.png">

**Comment by Aidan-OS** [comment]
This is ridiculous. I spent about 20 hours working on Erebus, particularly spending an insane amount of time trying to find the ores required. Forcing everyone to build one themselves essentially just forces only a single person to do anything in the Aether because _nobody_ on my team was willing to go through that grind again.

**Comment by WaitingIdly** [comment]
as of 2.3.0 there is a duplication recipe, please update to the latest version
