### ISSUE TITLE
Chime! Wait for me! Radius and Diagram

### ISSUE THREAD

**Issue by TheDoctor123t** [Divine-Journey-2/main#203]
**Location:**
In Chapter 2 in the description of the quest "Chime! Wait for me!" 

**Exact fix:**
Instead of "Radius of 8" it should be "Circumference of 8" (if it is intended to be 4 blocks away from the totem pole on both sides) and the diagram should be 4 blocks away instead of 5 blocks away

**Comment by sarperen** [comment]
Do you mean diameter of 8? Circumference of 8 doesn't really make sense in any situation.

**Comment by TheDoctor123t** [comment]
> 
> 
> Do you mean diameter of 8? Circumference of 8 doesn't really make sense in any situation.

Yea that makes more sense, though the diagram is still off and Radius of 8 is wrong (unless the diagram doesn't show all 8 blocks which why would they do that)

**Comment by ToasterKoishi** [comment]
Radius of 8 is correct. The corner chimes are located (5,5) away from the totem which is an actual distance of sqrt(5*5+5*5) = ~7.07 blocks away. It calculates using a sphere, not a cube, which is confusing since the 3-nearby-chimes things uses a cube, but the distance from the totem uses a sphere... but I digress.
