### ISSUE TITLE
Inferno Sword crafting recipe

### ISSUE THREAD

**Issue by uTa4u** [Divine-Journey-2/main#212]
**Modpack version:**
2.1.1

I think Inferno sword's recipe is too hard. It requires vanila redstone ore. I suggest you to change the recipe to require nether redstone ore. It makes sense AND still gates this sword behind Nether.

If you want to craft it then you have to visit Twilight Forest OR use Laser Drill OR use Vethea recipe. It makes no sense since stronger weapons can be obtained earlier.

This issue gets even worse if Twilight Forest is banned on the server

**Comment by thecodingchicken** [comment]
Note - the sword is unbreakable.  In addition, it does a fair bit of damage before the fire damage comes in to play.  Unless the actual dev team thinks it should be changed, I think it is fine.  
I can change the recipe to require oreRedstone instead of minecraft:redstone_ore, but still, only with their approval.  I'll prepare a pull request for that.

**Comment by Atricos** [comment]
The Inferno Sword can now use any type of Redstone Ore in its crafting recipe starting from version 2.2.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3449256
