### ISSUE TITLE
Quest Chapter 2 - Totemic is discriminating towards people with no rythm or disabilties

### ISSUE THREAD

**Issue by tjsd** [Divine-Journey-2/main#213]
The rituals required to progress are very hard to complete for people with no rythm or players of minecraft with reduced use of fingers/arms.

The progress should not be gated behind this kind of mechanic, my suggestion is to make hard crafting recipes that can skip the Ritual part of totemic for people that are not able to complete it.

**Comment by lily-es** [comment]
Big +1 on this. The mechanic is unfairly hard for some players. A way of getting around having to perform the rituals, or simply bypassing the chapter is the most basic courtesy that could be offered to people struggling with totemic.

**Comment by lily-es** [comment]
This would possibly include crafting recipes for Baykok's bow, as well as buffalo leather, teeth, and eagle feathers and bones. Or some form of optional quest book quest that would simply give you these materials on demand.

**Comment by Atricos** [comment]
You really don't need any rythm, just need to spam your right click on the Flute (in your off-hand)/Rattle (in your main hand), while hitting drums and jumping around.

Really, if you're looking the correct way, continously pressing space+right click, and slightly moving your cursor for the 2 drums without any rythm should be more than enough.

Unfortunately there are no configs in Totemic to make Ceremonies easier, however, if you switch the difficulty to Easy (if you're playing in Singleplayer or on a private server), Ceremonies will be more forgiving (give you more time to fill up the bar).

**Comment by lily-es** [comment]
Your response still ignores the fact that some people with motor issue simply cannot perform the movements necessary to complete the rituals, such as the movement combined with the switching instruments and spamming. I highly advise you to reconsider your stance on this, and add a way for people with motor difficulties to progress past this stage in the pack.

**Comment by Atricos** [comment]
Just cheat in the items.

I can't make quests that just give you the items, because that would be highly abusable.

**Comment by Atricos** [comment]
Hey, I'm sorry to seem ignorant, but you REALLY just gotta spam right click and space.

**Comment by lily-es** [comment]
I understand you are not trying to be ignorant, but you sort of are being anyway. Its not as simple as spamming and clicking space, there is keyboard inputs, mouse movement required to make sure you can hit the drums enough as well as using the instruments themselves. Its not as easy as just clicking space and right click, or no one would be struggling with this.

Either way, in the end cheating the items in is a solution in the end, but its a different case when people are playing on servers and dont have the ability to do that. Adding a quest to just give you the items would have no downside. The ppl who can do it and want to would do it the legit way, the people who find it too hard would just use the quest to get the items. You are worried about it being abused, but you tell the ppl who cant do it legit to just abuse cheats anyway. Whats the difference?

**Comment by tjsd** [comment]
I am an adult and I myself have no motor issues, but I have no rhythm. I have been trying for 2 hours with your spamming technique and it always stops on 95% music and does not proceed. Adding alternate recipes for the items required to progress is not unreasonable. Having a crafting recipe for the bow with hard to get materials that you need to cast and craft is an option for the bow. The buffalo hide and tooth can be gated behind other items that is rare, but does not require the rituals.

Also asking people to cheat in items because they find this part difficult is not exactly helping and completely ignoring the fact that this quest line does hinder a lot of people to progress/enjoy the pack.

**Comment by rguy98** [comment]
I'll repost what I said on the discord:

I agree heavily with Lily. I have slight motor issues and struggled heavily with finishing Totemic's questline to the point I nearly quit (was on multiplayer). It's not just right clicking and space, you have to worry about overusing instruments and doing the right thing, and the instructions are fairly vague.

I wouldn't make a quest that just gives the items but perhaps offer alternative crafting methods that offer a similar level of difficulty but help those who can't really do the ceremonies.

**Comment by lily-es** [comment]
After reading the other comments and reconsidering my stance, I agree 100% with what rguy and tjsd said. Cheating is not a solution, it is a non-solution. Telling people to cheat is just washing your hands of the issue. People should not be forced to cheat to get past the beginning of the modpack. And i mean "forced to". 

This is not a question of skill, or dedication, its literally a matter of impossibility. By not giving a solution to people who cannot realistically complete these rituals, for the reasons described above, you are excluding them from your playerbase entirely, and they cannot enjoy the pack. I agree that making a quest that just gives you the items is not the best solution, but at the very least you should provide an alternative crafting method for the required items.

I understand that you designed this pack according to your vision, and your vision includes going through totemic and doing the rituals to progress through the pack, but in the end, is it really worth it to preserve that vision when it means you will alienate a good chunk of people form playing your modpack? In the end the decision lies with you.

**Comment by Troxarus** [comment]
Ceremonies can be done by only moving a single finger. Assuming that Atricos is putting aside the struggle of people with disabilities is wrong and also rude, as ceremonies can be done quite easily if you do them correctly. I posted a video on discord that shows how anyone can finish ceremonies with ease. I'd suggest pinning the video so that people could actually look it up if they struggle with totemic.

**Comment by tjsd** [comment]
I watched @Troxarus video and tried to employ his tricks, this was my attempt 27 I think. 
It still fails, this is how it goes all the time.
https://youtu.be/D7K4deLk7WM

**Comment by lily-es** [comment]
The flute is supposed to go in the off hand, for what its worth

**Comment by tjsd** [comment]
> The flute is supposed to go in the off hand, for what its worth

Im not sure that matters, I still hear all 3 instruments.

**Comment by Troxarus** [comment]
@tjsd 
1. 2 drums instead of 3 make it easier.
2. You need to hold down space and the right mouse button and not let go.
3. Aim your mouse in a way where you'll hit both drums and a block/air beyond the second drum to activate the flute.
4. Put your flute in your off-hand.

Copying what I did should work out becasue ceremonies are not based on RNG.

**Comment by KleinGrrmpf** [comment]
I don't think that there is anything rythmic to Totemic. It is just exactly as Troxarus described it. Hold down Space and RMB, have the flute in the offhand and switch between the other two instruments in the main hand. And hit the drums whenever you can. Also, don't forget the twelve wind chimes. That's it. And when one of the instruments doesn't do anything anymore, just focus on the others more.

**Comment by ToasterKoishi** [comment]
As the beta-tester who literally reverse-engineered Totemic rituals from source code in order to devise that diagram you all see in the questbook, let me offer my input.

1) Due to the design of Totemic, it is literally impossible to complete the final ritual sometimes. If you get unlucky and none of the wind chimes decide to trigger in a particular attempt of the ritual... then the ritual actually becomes literally impossible. However, with the 12-chime setup that I devised, the chances of this happening are incredibly small, so I don't think this would ever be the cause of a failed ritual.

I do find it a huge flaw in Totemic to not allow the duration of rituals to be configured. In my ideal world, the durations would be much longer than they currently are. The way Totemic gates rituals is by making each instrument TYPE have a maximum amount of bar that they can contribute, so you need to have more instrument types in order to finish the last ritual, which requires a bar amount that can only be filled up by maxing out all but 1 instrument.

2) Following the previous point, it is therefore stated that the goal of the final ritual is to max out the bar contribution from each instrument type. Once an instrument type has contributed its maximum amount, it will contribute NOTHING MORE to the ritual and cause smoke particles to come out of the totem. It does require a fair degree of skill to notice this, but if you can, you should stop playing an instrument when you see that it's not contributing any more bar. For most players this will usually be the drums, which tend to max out like 1/2 or 2/3 of their way through the final ritual.

3) In the video @tjsd posted, you max out on the drums quite early (as most players do), which is why the rate of the top bar filling up suddenly slows down. At that point you should completely stop playing the drums because they will contribute nothing, and focus completely on playing the handheld instruments, since the drums eat the right-clicks that would have played one of the handheld instruments. When playing handheld instruments, it is noteworthy that, when holding the flute in main-hand, the bone whistle in off-hand will NOT play for whatever reason. What this means is that your goal should be to cycle between: play flute, switch to rattle, play rattle and bone whistle, switch to flute, repeat. Again, I do agree that it takes a fair degree of skill to notice which instruments are being played. And of course if you're good enough to notice which instruments are maxed out, then you can outright stop playing them. There may actually be an argument for not even putting the whistle in off-hand for more clarity when you've played it but you need to be really good at switching between three main-hand slots for this

4) There are other challenging encounters in the pack that are arguably much harder than the ritual (the Sun God or whatever boss comes to mind; there are also several difficult to cheese bosses in other mods) - but it is to note that none of them have a HARD TIME LIMIT. With enough gear and preparation, one could overpower those bosses by sheer force of being indestructible / dealing ridiculous damage through various means / cheesing, even the Sun God basically does no damage to you if you're well-prepared enough and despite the skill-oriented nature of defeating him you can just endure it out and rely on RNG. The final totemic ritual might actually have the highest mechanical skill *floor* of the pack, which is quite ridiculous!

As a game designer I agree that the ritual is too hard not just for people with disabilities but even for regular players, as not only is it actually difficult but the book is purposely vague on helping the player understand why they are failing.

Recommendation: Add recipe for Baycok spawn egg that consumes multiple or all of the Totemic instruments in its recipe. Spawning Baycok with a spawn egg into a cheese spot is a non-issue, you can trivially bait him into a cheese spot when summoning him normally. (To the point where I'd be more impressed with someone actually trying to fight him normally than just cheesing him tbh, imagine not cheesing every boss possible)

Better recommendation: open issue on Totemic to add config for tweaking time allowed to complete rituals.

**Comment by sdjjufdki** [comment]
even the rhythm game dev is saying this is too ridiculous lmao

**Comment by Xalior** [comment]
> Just cheat in the items.
> 
> I can't make quests that just give you the items, because that would be highly abusable.

Not viable on a server.

**Comment by Unhook** [comment]
> > Just cheat in the items.
> 
> Not viable on a server.

Just ask someone to help you then... Isn't that the whole point of playing on a server?

**Comment by Xalior** [comment]
> On 5 Sep 2021, at 00:01, Unhook ***@***.***> wrote:
> 
> 
> Just cheat in the items.
> 
> Not viable on a server.
> 
> Just ask someone to help you then... Isn't that the whole point of playing on a server?
> 
> 
No. Not all servers are cooperative. Not all server players live in the same timezone.

**Comment by Unhook** [comment]
> On 5 Sep 2021, at 00:01, Unhook ***@***.***> wrote: Just cheat in the items. Not viable on a server. Just ask someone to help you then... Isn't that the whole point of playing on a server?
> No. Not all servers are cooperative. Not all server players live in the same timezone.

If you're playing on a server isolated from everyone and never interact with anyone why are you even playing on a server in the first place. Sounds like a you-problem to me.

**Comment by Xalior** [comment]
> If you're playing on a server isolated from everyone and never interact with anyone why are you even playing on a server in the first place. Sounds like a you-problem to me.
> 
So, what you’re saying is being physically disadvantaged means I should learn to always have to ask for help? Sounds like you need to some empathy to me.

**Comment by Unhook** [comment]
> If you're playing on a server isolated from everyone and never interact with anyone why are you even playing on a server in the first place. Sounds like a you-problem to me.
> So, what you’re saying is being physically disadvantaged means I should learn to always have to ask for help? Sounds like you need to some empathy to me.

Yeah, that's totally what I said in my reply (not). You're crying about an issue that does not exist.

**Comment by Xalior** [comment]
> Yeah, that's totally what I said in my reply (not). You're crying about an issue that does not exist.
 You're being disablist. Way to break the github community guidelines Unhook.

https://docs.github.com/en/github/site-policy/github-community-guidelines#hate-speech-and-discrimination

**Comment by Unhook** [comment]
> > Yeah, that's totally what I said in my reply (not). You're crying about an issue that does not exist.
> 
> You're being disablist. Way to break the github community guidelines Unhook.
> 
> https://docs.github.com/en/github/site-policy/github-community-guidelines#hate-speech-and-discrimination

Oh here comes the 'disablist' card again. You have literally been given 2 EASY solutions: 1), if you're playing in singeplayer just cheat the items in. 2) If you're on server, ask someone to help you - it literally takes 2 minutes and the whole point of you playing on a server is interacting with other people.

If you refuse both it's indeed nobody issue besides your own.

**Comment by Troxarus** [comment]
Also, I completed the ritual by moving only a single finger. Everyone that plays minecraft should be able to move a single finger I assume, or else it would be impossible to play this game.

**Comment by DrTasslehoff** [comment]
use this exact setup: TWO drums, no more, no less. One block between each drum. You yourself stand one block away from the drum. Can use up to 12 chimes, but make sure to use leaves above them AND make sure no particles are being emitted from them. Questbook details this layout and how to do it. Flute/pan flute always goes in offhand, switch mainhand instrument between rattle/eagle if you have it. When jumping to proc jingle dress and holding right click you should be playing both held instruments and hitting both drums. Adjust your position or cursor position if that is not the case. Based on Troxarus video where he showed this, but more detailed so people can understand everything
![image](https://user-images.githubusercontent.com/42073120/132110775-f19fea56-772a-42ff-90fc-dea49936b6eb.png)

**Comment by Troxarus** [comment]
^This right here is probably the best explanation you could look for. Just do what the person above me said and you'll be able to complete ceremonies with ease

**Comment by Nidaelie** [comment]
+1 of player leaving the modpack due to this thing... have tried all.. 2 drums 3 5... 3 chimes 12 (always 3 congested using quetbook pattern or sphere pattern like shows in other github chimes reports)

no way to do solo, in multiplayer....... what to expect from the rest of the modpack...
