### ISSUE TITLE
[Balance Request] Dummy dropping free coagulated blood using bloody mary modifier.

### ISSUE THREAD

**Issue by Akira013** [Divine-Journey-2/main#217]
**Modpack version:**
2.1.1

**Describe the request:**
Using the Bloody Mary modifier from signalum on an unbreakable tool and hitting the test dummy one can farm coagulated blood.

**Reasons why this should be changed:**
Too easy to farm coagulated blood.

**Describe alternatives you've considered:**
Make the dummy not drop coagulated blood, if its possible.

**Additional context:**
None

**Comment by thecodingchicken** [comment]
Looking into it.  Think I have a few ideas.  

I don't know if it's possible to disable a drop from a specific mob, especially since the drop isn't from the mob itself, but something the sword has.  
As such, I would recommend disabling the modifier entirely, which may mess with people's tools who might have it already, but I don't know of a better solution.  
I'll work on it in a bit

**Comment by WaitingIdly** [comment]
You can farm mobs completely safely without too much effort. This is not an issue, and we do not want to disable the modifier.

**Comment by thecodingchicken** [comment]
Agreed.  It is a useful modifier.  Just an unintended feature.  
I think the issue can be closed now
