### ISSUE TITLE
Vanilla Ender Chest doesn't accept Itemducts & Logistical Pipes

### ISSUE THREAD

**Issue by EagleHamlet** [Divine-Journey-2/main#241]
**Modpack version:**
2.2.0

**Description:**
The vanilla ender chest doesn't accept the logistical item pipes from Mekanism & Itemducts. I haven't tried any other pipes. 

**Steps to reproduce:**
1. Put vanilla ender chest down
2. Try to connect any pipes
3. Nothing happens

**Expected behavior:**
They should connect

**Screenshots:**
![image](https://user-images.githubusercontent.com/90133613/132134019-cdc6e17b-aec9-4c4c-b587-ef4ec77168ae.png)

**Additional context:**
Nothing

**Comment by King65868** [comment]
Vanilla Ender chest isn’t supposed to be automatable.

**Comment by WaitingIdly** [comment]
Not only is this intended by the mod, there is no realistic way for a mod to do this.

**Comment by ToasterKoishi** [comment]
As a further explanation to the ticket author, the issue is *how does the pipe know WHOSE ender chest to pull items out of?*

I disagree with WaitingIdly in that a mod author could implement this by saving the user that placed down a pipe with the pipe, and when a pipe is next to an ender chest, the pull items from the owning player's ender chest inventory. However, this is abusable because player 2 could put an ender chest next to a pipe that player 1 owns, then route that pipe to a regular chest, and then that would allow player 2 to steal items from player 1's ender chest inventory, which breaks the purpose of the ender chest inventory being safe from other players.
