### ISSUE TITLE
Add Building gadgets to the pack

### ISSUE THREAD

**Issue by Noxtralis** [Divine-Journey-2/main#273]
Even if it's gated, I would still love for this to be a feature.

**Comment by aacidic** [comment]
I would love to see this too, it's a very useful tool for building (more than the wands in my opinion at least) but I can see how it may end up being a bit hesitant to add, since we already have some building tools - I'm not the one deciding what is added in the pack but to WaitingIdly, if you don't know which of the two building mods (building gadgets or better builders wands) to choose I think it'd be best to set up a poll in the discord for it :D

**Comment by oliver-hale** [comment]
Completely agree- Building Gadgets is essential in building big bases. There is no other way to easily copy and paste large areas in the pack. RFtools builder could work, but that is heavily gated for progression reasons. BG could be a more early and accessible option (at early Mekanism perhaps?) that would allow for easy building.

It really isn't overpowered. All it helps with is building and voiding large areas. This would only enhance the Divine Journey 2 experience, imo
