### ISSUE TITLE
Bugged Spellbinding Cloth

### ISSUE THREAD

**Issue by JohanniklasLp** [Divine-Journey-2/main#289]
**Modpack version:**
2.3.1

**Description:**
Crafting wildwood blocks leaves spellbinding cloths with bugged/nonexistent texture behind

**Steps to reproduce:**
1. Get an Advanced Crafting Table
2. Input the wildwood block crafting table and finish the craft

**Expected behavior:**
For the spellbinding cloth to either be used up or not be bugged, whichever is the intended behaviour.

**Screenshots:**
![bug](https://user-images.githubusercontent.com/57828910/133178972-22e4c68b-07e2-41fa-866c-4c7ab05df248.png)

**Comment by Atricos** [comment]
Unfortunately I couldn't make Spellbinding Cloth work in the recipe, because Extended Crafting doesn't implement IIngredientTransformers. Related issue: https://github.com/BlakeBr0/ExtendedCrafting/issues/126.

However I changed the Spellbinding Cloths to Manaweave Cloths in 2.4.0 (https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3464189), which fixes the issue (and makes the recipe slightly cheaper as well).

**Comment by JohanniklasLp** [comment]
![grafik](https://user-images.githubusercontent.com/57828910/134094902-f691a799-497f-4957-8e40-27aa329a4ca6.png)
Same issue when crafting enchanted fabric in the arcane workbench

**Comment by Atricos** [comment]
Fixed in 2.5.0.
