### ISSUE TITLE
Skythern dungeon can still be partly skipped

### ISSUE THREAD

**Issue by Bosfik** [Divine-Journey-2/main#394]
**Modpack version:**
2.5.0.

**Description:**
You've removed the knowledge of the sky from chests loot tables, but there are also shulker boxes inside, which sometimes contain it.

**Steps to reproduce:**
^

**Expected behavior:**
Knowledges of the sky should not appear in shulker boxes

**Comment by Bosfik** [comment]
And for some reason i found it right now in a bone chest

**Comment by Ringedtech203** [comment]
Are you sure you are in a dungeon that was generated after the 2.5 update?

**Comment by Bosfik** [comment]
yes, i've unlocked skythern today

**Comment by Atricos** [comment]
I accidentally saved a previously pregenerated version of the Skythern dungeon in 2.5.0 (the loot wasn't random and still included Knowledges of the Sky) - I fixed it now in 2.6.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3480373 The loot should be random and shouldn't contain Knowledges of the Sky (except of course, the Boss should hold some).

I recommend regenerating Skythern (yet again) on servers because of this. You can do this by deleting the `world/Skythern` folder, and restarting the server.
