### ISSUE TITLE
Add Skyroot Log recipe for Livingwood

### ISSUE THREAD

**Issue by 40110** [Divine-Journey-2/main#420]
**Modpack version:**
2.6.0

**Describe the request:**
Add a recipe to transform Skyroot Log into Livingwood

**Reasons why this should be added:**
Every other dimensional wood type can be used, so I don't see why not

**Describe alternatives you've considered:**

**Additional context:**

**Comment by KleinGrrmpf** [comment]
You are supposed to use Golden Oak and not Skyroot. (Except if Atri forgot that one)

**Comment by 40110** [comment]
Why?

**Comment by KleinGrrmpf** [comment]
I don't know. Maybe because they are more special? I opened a bugreport in the beta phase and let Atri know in the additional context of that issue that he might want to add Skyroot Logs to the Livingwood recipe as well, but he didn't. So either he didn't read the additional context or he didn't want to. 
Either way, here's my issue:
https://github.com/Divine-Journey-2/main/issues/153

**Comment by Atricos** [comment]
Skyroot Log can now be transformed into Livingwood in 2.7.0: https://www.curseforge.com/minecraft/modpacks/divine-journey-2/files/3486165
