### ISSUE TITLE
Enable Liquified Coralium Ore

### ISSUE THREAD

**Issue by luciscout** [Divine-Journey-2/main#428]
**Modpack version:**
2.6.0

**Describe the request:**

Liquified Coralium Ore is currently disabled in line 1106 of abyssalcraft.cfg. This should be enabled by setting the value to true.

**Reasons why this should be changed:**

You need a lot of Refined Coralium throughout the pack, and the amount of resources per ingot is quite high.

**Describe alternatives you've considered:**

- Have Coralium Seeds give Refined Coralium instead (or a separate seed for this?)
- Reduce the crafting cost of Chunk of Coralium, either entirely or by some alternate crafting recipe.
- Increase the output of each Chunk, either entirely or by one of the later recipes
- Remove Liquified Coralium entirely from JEI (worst)

**Additional context:**

![image](https://user-images.githubusercontent.com/77116048/136501369-87c3c2de-83bc-4c66-8af0-a8a2b33b725f.png)

**Comment by 1234abcdcba4321** [comment]
It could be interesting to make it possible to get the ore through other means (like an orechid / #425 ). Though this would basically require making one of those two, and that's probably somewhat laggy.

The main annoying part of refined coralium is the need for abyssal stone to create it, since there's no easy way to get that until Chapter 27 and you need a whole lot of offensa before that point.

**Comment by Atricos** [comment]
First of all, Liquified Coralium Ore is enabled because of RFTools Dimensions. Secondly, while this recipe might seem intimidating,
![image](https://user-images.githubusercontent.com/24854267/136665764-3aae87f1-b651-45f2-b0ec-28f57f4070d2.png)
all of the ingredients are quarryable / farmable. Coralium Gems come from Coralium Ore (could be Mining Laser'ed up), Abyssal Stone can easily be quarried out, Ender Alloy (Basic) is just Osmiridium - Iridium (Laser Drill / later Magical Crops) and Enderium (Quarry + Mobfarm / later Magical Crops).
It then gives 2 Liquified Coralium Ingots:
![image](https://user-images.githubusercontent.com/24854267/136665812-ac6d8785-b88f-4042-8a8b-c9aa948b35ef.png)
If this is a large material cost, I can decrease the amount of resources needed, but I don't plan to make the recipe significantly easier.
