### ISSUE TITLE
EnderIO Item Conduits Not Working Properly

### ISSUE THREAD

**Issue by AgentFred104** [Divine-Journey-2/main#445]
First check if your problem has been submitted before, or if it's a Known Issue. If it already exists, please don't submit. Then check if you're on the latest Divine Journey 2 version. If not, please update first and see if your issue's been fixed. If not, fill out the form below by REWRITING the text below the titles, and delete this text as well.

**Modpack version:**
2.6.0

**Description:**
When Ender IO item conduits are placed in the overworld, they do not render fully or connect to any other blocks around them.

**Steps to reproduce:**
1. Open the game and enter a multiplayer world.
2. Place down an item conduit.

**Expected behavior:**
Item Conduit normal behavior - to connect to other conduits and blocks nearby, and to render normally.

**Additional context:**
This problem is encountered on a multiplayer world (ModRealms) run using Sponge.

**Comment by Atricos** [comment]
We had the same issue when we had TickCentral (and Lag Goggles) in the pack. It was likely added to your instance.

Lag Goggles isn't even too necessary, because we have Spark instead, so you can measure performance with that.

By removing Tick Central, your Conduits will work again. But since it's not  in the pack by default, I'm gonna close the issue.
