### ISSUE TITLE
Converting Aluminum and Silver Ore into Liquified Coralium Ore

### ISSUE THREAD

**Issue by RexxyJ** [Divine-Journey-2/main#513]
**Modpack version:**
2.8.0-fixed

**Describe the request:**
Remove the ability to convert Aluminum and Silver Ores into Liquified Coralium Ore by having them, in block form, come into contact with Liquid Coralium.

**Reasons why this should be changed:**
This bypasses the need to craft the Chunk of Coralium, which is the intended way of getting Refined Coralium ingots.

**Describe alternatives you've considered:**
None I can think of.

**Additional context:**
This interaction is coded into the mod, so I'm not *entirely* sure that there's a way to prevent it, but I thought I would at least bring attention to it.

**Comment by ByThePowerOfScience** [comment]
Hi! I'm just going to give my input, which is: dear god no please don't.

With the Chunk of Coralium method, you have to use 162 Coralium Gems per one Damage Reagent, and 486 gems per Offensive Core or Tablet.  With the maximum amount of Coralium Gems you can reasonably get per ore being 2-5 gems (though Fortune V occasionally gives 15), that means you need 32 ore per Reagent and 98 ore per single tablet.  For perspective, the Digital Miner - the most efficient way to get Coralium Ore - only gives 400 ore (or four tablets) at best. 

There is no way to passively automate Coralium in such large quantities before Astral Sorcery, meaning that for the entirety of Blood Magic and Thaumcraft, I have needed to AFK beside my Digital Miner for around 10 minutes - where I can't do anything else mind you, because I have to keep the dimension loaded - every time I want to craft Mystical Tablets.  The Liquified Ore method is the only way to passively automate this minor resource for the duration that it's required.

If anything, I'd suggest adding a loading screen tip clueing people in that this is an option.  I only learned about the feature because of this ticket, and it's removed the hour of AFKing that I've had to spend every day, letting me continue on with this amazing pack.

**Comment by King65868** [comment]
Coralium can come from the Quantum quarry and can be mined using the builder, digital miner is the worst way to do it

**Comment by ByThePowerOfScience** [comment]
I will say, chunkloading isn't an option on servers, but since this is primarily designed for single-player that's a moot point. 
 Regardless, in the quantities that we need it, any buffer we fill will need to be refilled much more often than any other minor resource in this pack.

**Comment by KleinGrrmpf** [comment]
Wait, you can do that? Please don't remove it, it really takes out the grind. And I would back up PowerOfScience with the loading tip screen. Great idea!

**Comment by Atricos** [comment]
Disabled this in 2.10.0, but made items crafted from Liquidfied Coralium Ore yield 4x as much.
