### ISSUE TITLE
Artificial Scarab Body

### ISSUE THREAD

**Issue by SenzakiLG** [Divine-Journey-2/main#546]
Hello, I arrived at the quest "Mystery of the Scarab II", but when I went to craft the artificial scarab body, the gold rod of the "immersive" was not being recognized as an equivalent rod of the "LightningCraft", moreover the rod of "LightningCraft" has no way to craft.

I'm now at the 2.9.0 version and still have no way to craft the rod.

**Comment by WaitingIdly** [comment]
In game, JEI displays only one gold rod. In the scripts, there is only ever one gold rod (lightningcraft). When searching all IE items, there is no gold rod. On the IE github for 1.12.2 there exists no "gold rod" texture. IE in 1.12 does not have a gold rod. 
Immersive Posts, a mod not in this pack, adds a Gold Rod - but as this means you modified the pack, such errors are on you.

Please respond with additional information.

**Comment by rickspencer** [comment]
When you make a gold rod in IE it creates the lightning craft one, not an IE one that's why you don't see one in IE @WaitingIdly 
I did this in 2.8.0 without any issues and now have upgraded to 2.9.1 and just remade the artificial scarab body again with no issues. @SenzakiLG don't slap me but are you absolutely sure you are using 'industrial leather' and not treated leather?
